services:

  postgres:

    image: postgres:17

    container_name: cloudstorage-postgres

    restart: always

    environment:
      POSTGRES_DB: cloudstorage
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - cloudstorage_postgres_data:/var/lib/postgresql/data

volumes:
  cloudstorage_postgres_data: